### ISSUE TITLE
How do i add apps in the app menu

### ISSUE THREAD

**Issue by SAUCYSOUP76** [morgant/mlvwm#3]
trying to add firefox into the app menu, can't figure out how.
Using the arch AUR version.

**Comment by morgant** [comment]
Judging by the ArchLinux AUR [`PKGBUILD` for `mlvwm`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mlvwm), it looks like the `sample_rc/Mlvwmrc*` files get installed in `/usr/share/mlvwm/`.

To add Firefox, or any other app to the Apple/app menu, you'd want to edit the `Menu Apple […] END` block to add another line such as:

    "Firefox" Action Exec "firefox" exec firefox, Icon mini-nscape.xpm

Of course, it doesn't look like the `PKGBUILD` installs the mini icons, so I'm not sure if that Icon (or any others) will be accessible.

I hope that at least points you in the right direction.

**Comment by SAUCYSOUP76** [comment]
I installed your mlvwmrc mod, thanks by the way. I'll try this now.

**Comment by SAUCYSOUP76** [comment]
Issue is solved

**Comment by morgant** [comment]
@SAUCYSOUP76 If you're using my [mlvwmrc](https://github.com/morgant/mlvwmrc) config files (which is still very much under development and expected to change), the `Menu Apple […] END` block would be found in the various `~/.mlvwm/themes/` files instead.

Glad you were able to resolve the issue!

**Comment by SAUCYSOUP76** [comment]
Yeah i figured it out got to say i love your file structure, at first i was lost but now i understand it it's brilliant please don't change it.

**Comment by morgant** [comment]
@SAUCYSOUP76 I'm glad you like it! I don't expect it to change significantly, if at all.
