### ISSUE TITLE
Update README to reflect the updated AUR

### ISSUE THREAD

**Issue by mechanical64** [morgant/mlvwm#32]
As you know, the AUR was last updated in around 2015. It was updated today to 0.9.4, the latest release. It would be a good idea to update the "installation" section to reflect that.

**Comment by morgant** [comment]
@mechanical64 Huge thanks for updating the AUR package and letting me know! I'll definitely add that to the installation section.

On a related note, I'll likely link to the [`mlvwm` project page on Repology](https://repology.org/project/mlvwm/versions) (and maybe integrate the [badge](https://repology.org/project/mlvwm/badges)) to make sure any new/updated packages are more immediately accessible.

**Comment by morgant** [comment]
@mechanical64 My _sincerest apologies_ for how long it has taken me to address this and _many thanks_ for updating the package in AUR!

I have now updated the README to list OpenBSD, NetBSD, Arch Linux, and NixOS as having packages, plus linked to repology.org. I also embedded the Repology versions badge for mlvwm.
