### ISSUE TITLE
Can't open config file initrc

### ISSUE THREAD

**Issue by SAUCYSOUP76** [morgant/mlvwm#4]
appaears at the top then disappears.

**Comment by morgant** [comment]
This is actually an issue with the [mlvwmrc](https://github.com/morgant/mlvwmrc) config files. Would you mind opening a ticket on that project and I'll try to address it soon?

**Comment by SAUCYSOUP76** [comment]
Done, also when I'm using mlvwm there's no background just solid black which is repeatable across all three themes is that a problem for this project or mlvwmrc?

**Comment by morgant** [comment]
@SAUCYSOUP76 Thanks! I believe the background color issue would be mlvwmrc. Probably worth adding a separate ticket for that as I was testing on OpenBSD and had a solid grey background, so I should look into it.

**Comment by morgant** [comment]
Resolved in [mlvwmrc Issue #2](https://github.com/morgant/mlvwmrc/issues/2).
